import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { ModalProvider } from '../components/ModalContext';
import Modal from '../components/Modal';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Добавляем ссылку на favicon */}
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Оборачиваем всё в ModalProvider */}
        <ModalProvider>
          {children}
          {/* Вставляем компонент Modal */}
          <Modal />
        </ModalProvider>
      </body>
    </html>
  );
}
